### ISSUE TITLE
[1.16.5] Crash with custom mod

### ISSUE THREAD

**Issue by 4nyNoob** [Flemmli97/MobBattle#27]
### Modloader

Forge

### Minecraft version

1.16.5

### Modloader version

36.2.39

### Mod version

1.16.5-2.3.8.3

### Description

My custom mobs mob isn't playing well with the mobbattle mod, sometimes when assigning my custom mobs to a team there's a:

```log
Details:
	Entity Type: jayemod:camera_woman (com.any.jayemod.entity.custom.CameraWomanEntity)
	Entity ID: 8
	Entity Name: Camera Woman
	Entity's Exact location: -568.44, 144.00, 141.15
	Entity's Block location: World: (-569,144,141), Chunk: (at 7,9,13 in -36,8; contains blocks -576,0,128 to -561,255,143), Region: (-2,0; contains chunks -64,0 to -33,31, blocks -1024,0,0 to -513,255,511)
	Entity's Momentum: 0.00, -0.08, -0.05
	Entity's Passengers: []
	Entity's Vehicle: ~~ERROR~~ NullPointerException: null
```

### Steps to reproduce

1. spawn a bunch(50 or more) of mobs from my mod

2.  have someone joining via LAN

3. assign all of the mobs or just a part of them to a team

4. crash

### Mods that might affect the issue

[The mod that's causing problems](https://drive.google.com/file/d/1TU0hm3EVUQnYHS_mSVDAbTMDGTbGpm9J/view?usp=sharing)

this is a mod that i'm developing by myself, so i believe that the problem lies on my lack of knolwedge, anyways, here's the code for the entity that's freaking out

[CameraWomanEntity.java](https://gist.github.com/4nyNoob/76959356d9ba42aaa1a7a9a18c239b03)

### Logs

https://paste.gg/p/anonymous/601e466962484485be9a992a3d189028

**Comment by Flemmli97** [comment]
something in the look controller is null. this is all i can give though as 1.16.5 is out of support

**Comment by ScreamingMC** [comment]
The ticking entity crash when mob battle mods interact with your entity stems from a few specific issues in your GeckoLib animation controller logic and entity state handling:

### 1. Modifying Animation Controllers inside Predicates (`markNeedsReload()`)

In your `attackPredicate`, calling `event.getController().markNeedsReload()` or dynamically altering states inside an active animation event callback can trigger concurrent modification exceptions or state desynchronization when external mods force target switches or rapid combat simulations.

### 2. Thread/Client-Server State Desync (`isSwingInProgress`)

`isSwingInProgress` is heavily managed by client/server packets and attack cooldown ticks. When mob battle automation plugins or mods simulate rapid-fire attacks or force mob AI states, `isSwingInProgress` can desync, causing null pointer exceptions or improper animation controller resets.

---

### Solution

Refactor your `attackPredicate` to use standard GeckoLib triggerable animations or conditional state checks without unsafe controller reloads.

1. **Update the Attack Predicate:** Fixes state crashes.
Replace your `attackPredicate` method with a cleaner implementation that checks loop settings safely:

```java
public PlayState attackPredicate(AnimationEvent event) {
    if (this.dead || this.getHealth() <= 0) {
        return PlayState.STOP;
    }
    return PlayState.CONTINUE;
}

```


2. **Trigger Attack Animations via Goal or Packet:** Safe alternative.
Instead of hooking into `isSwingInProgress`, handle the attack animation trigger inside `attackEntityAsMob`:

```java
@Override
public boolean attackEntityAsMob(Entity entityIn) {
    boolean success = super.attackEntityAsMob(entityIn);
    if (success && !this.world.isRemote()) {
        // Trigger your attack controller animation safely here if using GeckoLib's sync features
    }
    return success;
}

```


*Verification:* Check your server log file (`latest.log`) after launching a mob battle to confirm that the `NullPointerException` or `ConcurrentModificationException` pointing to your entity class lines has stopped appearing.

Analysis done by Gemini.
