### ISSUE TITLE
[Feature Request]: Longer ranged Mob Battle Staff + Group

### ISSUE THREAD

**Issue by JamesDawnshine** [Flemmli97/MobBattle#39]
### Suggestions

Make the Mob Stick + Group have a longer range, because there's seemingly no way to hit mobs like the Ender Dragon with it because no matter how close I get, I can't seem to use the staff on it.

### Solution

It'll make mobs like the Ender Dragon easier to use the sticks/staffs on for mob battles.

**Comment by Flemmli97** [comment]
that is because the big hitbox is the enderdragon entity which is not selectable. and the small hitboxes are its part which you target when attacking it. and the small parts are not mobs so they are not selectable with the stick. you can use the army item instead but using the dragon for fights is useless since the dragon is immune to non player or explosion damage
